[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/tmp/supervisord.pid

[program:xvfb]
priority=10
directory=/
command=/usr/bin/Xvfb :1 -screen 0 1280x720x24
autostart=true
autorestart=true
stopsignal=QUIT
stdout_logfile=/var/log/xvfb.log
stderr_logfile=/var/log/xvfb.err

[program:startxfce4]
priority=20
directory=/
command=/usr/bin/startxfce4
autostart=true
autorestart=true
stopsignal=QUIT
environment=DISPLAY=":1",HOME="/root"
stdout_logfile=/var/log/xfce4.log
stderr_logfile=/var/log/xfce4.err

[program:x11vnc]
priority=30
directory=/
command=/usr/bin/x11vnc -display :1 -forever -shared -nopw -rfbport 5900 -xkb
autostart=true
autorestart=true
stopsignal=QUIT
environment=DISPLAY=":1"
stdout_logfile=/var/log/x11vnc.log
stderr_logfile=/var/log/x11vnc.err

[program:websockify]
priority=40
directory=/
command=/system/conf.d/websockify.sh
autostart=true
autorestart=true
stopsignal=QUIT
stdout_logfile=/var/log/websockify.log
stderr_logfile=/var/log/websockify.err
